import type { CslItem } from '../src'

/** Je ein Beispiel pro Typ, den das manuelle Formular anbietet. */
export const fixtures: CslItem[] = [
  {
    id: 'book',
    type: 'book',
    title: 'Grundlagen der Informatik',
    author: [
      { family: 'Müller', given: 'Anna' },
      { family: 'Schmid', given: 'Peter' },
    ],
    edition: '3',
    publisher: 'Springer Vieweg',
    'publisher-place': 'Berlin',
    issued: { 'date-parts': [[2021]] },
  },
  {
    id: 'article',
    type: 'article-journal',
    title: 'Deep learning',
    author: [
      { family: 'LeCun', given: 'Yann' },
      { family: 'Bengio', given: 'Yoshua' },
      { family: 'Hinton', given: 'Geoffrey' },
    ],
    'container-title': 'Nature',
    'container-title-short': 'Nature',
    volume: '521',
    issue: '7553',
    page: '436-444',
    issued: { 'date-parts': [[2015, 5, 28]] },
    DOI: '10.1038/nature14539',
  },
  {
    id: 'conference',
    type: 'paper-conference',
    title: 'Attention is all you need',
    author: [
      { family: 'Vaswani', given: 'Ashish' },
      { family: 'Shazeer', given: 'Noam' },
    ],
    'container-title': 'Advances in Neural Information Processing Systems',
    editor: [{ family: 'Guyon', given: 'Isabelle' }],
    publisher: 'Curran Associates',
    'publisher-place': 'Red Hook, NY',
    page: '5998-6008',
    issued: { 'date-parts': [[2017, 12]] },
  },
  {
    id: 'webpage',
    type: 'webpage',
    title: 'Zitieren und Referenzieren',
    author: [{ literal: 'Hochschule Musterstadt' }],
    'container-title': 'Bibliothek Hochschule Musterstadt',
    URL: 'https://www.example.org/bibliothek/zitieren',
    accessed: { 'date-parts': [[2024, 3, 12]] },
  },
  {
    id: 'standard',
    type: 'standard',
    title: 'Qualitätsmanagementsysteme – Anforderungen',
    author: [{ literal: 'Deutsches Institut für Normung' }],
    genre: 'DIN EN ISO',
    number: '9001:2015',
    publisher: 'Beuth',
    'publisher-place': 'Berlin',
    issued: { 'date-parts': [[2015, 11]] },
  },
  {
    id: 'preprint',
    type: 'article',
    title: 'Attention is all you need',
    author: [{ family: 'Vaswani', given: 'Ashish' }],
    publisher: 'arXiv',
    number: 'arXiv:1706.03762',
    issued: { 'date-parts': [[2017]] },
    URL: 'https://arxiv.org/abs/1706.03762',
  },
  {
    id: 'thesis',
    type: 'thesis',
    title: 'Literaturverwaltung im Studium',
    author: [{ family: 'Keller', given: 'Lena' }],
    genre: 'Bachelorarbeit',
    publisher: 'Hochschule Musterstadt',
    'publisher-place': 'Musterstadt',
  },
  {
    id: 'collection',
    type: 'book',
    title: 'Künstliche Intelligenz im Unternehmen',
    editor: [
      { family: 'Huber', given: 'Sandra' },
      { family: 'Frei', given: 'Jonas' },
    ],
    'collection-title': 'Edition Wirtschaftsinformatik',
    'collection-number': '12',
    publisher: 'Springer Gabler',
    'publisher-place': 'Wiesbaden',
    issued: { 'date-parts': [[2023]] },
  },
  {
    id: 'chapter',
    type: 'chapter',
    title: 'Datenschutz in Sprachmodellen',
    author: [{ family: 'Brunner', given: 'Lea' }],
    'container-title': 'Künstliche Intelligenz im Unternehmen',
    editor: [
      { family: 'Huber', given: 'Sandra' },
      { family: 'Frei', given: 'Jonas' },
    ],
    edition: '2',
    publisher: 'Springer Gabler',
    'publisher-place': 'Wiesbaden',
    issued: { 'date-parts': [[2023]] },
    page: '45-67',
  },
]
