/**
 * Alle UI-Texte an einem Ort. Für eine Übersetzung diese Datei kopieren (z. B. `en.ts`)
 * und in den Apps austauschen. `appName` ist der zentrale Punkt zum Umbenennen.
 */
export const de = {
  appName: 'OpenLitBase',
  common: {
    loading: 'Lädt …',
    save: 'Speichern',
    cancel: 'Abbrechen',
    create: 'Anlegen',
    search: 'Suchen …',
    comingSoon: 'Folgt in einer späteren Phase.',
    error: 'Etwas ist schiefgelaufen.',
    retry: 'Erneut versuchen',
  },
  nav: {
    project: 'Projekt',
    overview: 'Übersicht',
    items: 'Titel',
    bibliography: 'Literaturverzeichnis',
    protocol: 'Rechercheprotokoll',
    termMatrix: 'Begriffsmatrix',
    projectSettings: 'Projekteinstellungen',
    settings: 'Einstellungen',
    toggleSidebar: 'Seitenleiste umschalten',
  },
  workspace: {
    label: 'Projekte',
    switch: 'Projekt wechseln',
    create: 'Neues Projekt',
    none: 'Kein Projekt',
  },
  onboarding: {
    title: 'Lege dein erstes Projekt an',
    description:
      'In OpenLitBase passiert alles innerhalb eines Projekts – etwa deiner Bachelorarbeit: Titel, Literaturverzeichnis, Rechercheprotokoll und Begriffsmatrix.',
    create: 'Projekt anlegen',
  },
  empty: {
    noMatchesTitle: 'Keine Treffer',
    noMatchesDescription: (query: string) => `Kein Titel passt zu „${query}“.`,
    clearSearch: 'Suche zurücksetzen',
    bibliographyTitle: 'Noch nichts zu zitieren',
    bibliographyDescription:
      'Das Literaturverzeichnis entsteht automatisch aus den Titeln dieses Projekts – im Zitierstil des Projekts.',
    toItems: 'Zu den Titeln',
    protocolTitle: 'Noch keine Titel im Projekt',
    protocolDescription:
      'Sobald Titel im Projekt sind, ordnest du sie hier ein – für die Liste der recherchierten Titel im Rechercheprotokoll.',
    termMatrixTitle: 'Noch keine Begriffsmatrix',
    termMatrixDescription:
      'Sammle zu jedem Teilthema Synonyme, Ober- und Unterbegriffe und englische Übersetzungen – daraus entsteht dein Suchstring.',
    comingSoon: 'In Vorbereitung',
    attachmentsTitle: 'Keine Anhänge',
    attachmentsDescription: 'Lade das PDF zu diesem Titel hoch, um es direkt im Browser zu öffnen.',
    tokensTitle: 'Noch keine API-Tokens',
    tokensDescription: 'Erzeuge einen Token, um die Browser-Extension oder das Word-Add-in zu verbinden.',
    domainsTitle: 'Noch keine Institution freigegeben',
    domainsDescription: 'Ohne freigegebene Domain kann sich niemand registrieren.',
    usersTitle: 'Noch keine Konten',
    usersDescription: 'Sobald sich jemand registriert, erscheint das Konto hier.',
    usersNoMatch: 'Kein Konto passt zur Suche.',
    itemNotFoundTitle: 'Titel nicht gefunden',
    itemNotFoundDescription: 'Der Titel wurde entfernt oder gehört nicht zu diesem Projekt.',
  },
  userMenu: {
    open: 'Konto-Menü',
    localMode: 'Lokaler Modus (ohne Login)',
    settings: 'Einstellungen',
    admin: 'Administration',
  },
  theme: {
    toggle: 'Farbschema wechseln',
    light: 'Hell',
    dark: 'Dunkel',
    system: 'System',
  },
  projects: {
    createTitle: 'Neues Projekt',
    createDescription: 'Projekte bündeln Titel, Rechercheprotokoll und Begriffsmatrix einer Arbeit.',
    nameLabel: 'Name',
    namePlaceholder: 'z. B. Bachelorarbeit',
    created: 'Projekt angelegt',
    notFound: 'Projekt nicht gefunden',
    tabItems: 'Titel',
    tabBibliography: 'Literaturverzeichnis',
    actions: 'Projektaktionen',
    rename: 'Umbenennen',
    renameTitle: 'Projekt umbenennen',
    citationStyle: 'Zitierstil',
    styleDescription: 'Gilt für Literaturverzeichnis und Word-Add-in dieses Projekts.',
    useAccountDefault: 'Account-Standard',
    delete: 'Projekt löschen',
    deleteConfirm:
      'Das Projekt wird mit Rechercheprotokoll und Begriffsmatrix gelöscht – ebenso alle Titel, die nur in diesem Projekt vorkommen.',
    settingsTitle: 'Projekteinstellungen',
    generalTitle: 'Allgemein',
    dangerTitle: 'Projekt löschen',
    dangerDescription: 'Kann nicht rückgängig gemacht werden.',
    deleted: 'Projekt gelöscht',
    saved: 'Projekt gespeichert',
  },
  items: {
    empty: 'Noch keine Titel vorhanden.',
    emptyTitle: 'Noch keine Titel in diesem Projekt',
    emptyDescription: 'Füge Literatur per DOI, ISBN oder Link hinzu, erfasse sie manuell oder importiere einen Export aus Citavi, Zotero oder EndNote.',
    noMatches: 'Keine Treffer.',
    untitled: '(ohne Titel)',
    columns: {
      title: 'Titel',
      authors: 'Autor:innen',
      year: 'Jahr',
      type: 'Typ',
      tags: 'Tags',
    },
    addPlaceholder: 'DOI, ISBN, arXiv-ID, PMID oder URL einfügen …',
    add: 'Hinzufügen',
    adding: 'Suche Metadaten …',
    added: 'Titel hinzugefügt',
    alreadyExists: 'Titel war schon in der Bibliothek',
    detected: {
      doi: 'DOI',
      isbn: 'ISBN',
      arxiv: 'arXiv',
      pmid: 'PubMed',
      url: 'URL',
    },
    manual: 'Manuell',
    manualTitle: 'Titel manuell erfassen',
    manualDescription: 'Typ wählen und die bekannten Angaben ausfüllen.',
    typeLabel: 'Typ',
    actions: 'Aktionen',
    open: 'Öffnen',
    addToProject: 'Auch in anderes Projekt übernehmen',
    addedToProject: 'Ins Projekt übernommen',
    remove: 'Aus Projekt entfernen',
    removeConfirmTitle: 'Titel aus dem Projekt entfernen?',
    removeConfirm:
      'Der Titel wird aus diesem Projekt entfernt. Kommt er in keinem anderen Projekt vor, wird er samt Notizen und Anhängen gelöscht.',
    removed: 'Titel entfernt',
    back: 'Zurück',
    metadata: 'Metadaten',
    saved: 'Gespeichert',
    tags: 'Tags',
    tagPlaceholder: 'Tag eingeben, Enter zum Hinzufügen',
    notes: 'Notizen',
    notesPlaceholder: 'Eigene Notizen zu diesem Titel …',
    attachments: 'Anhänge',
    noAttachments: 'Keine Anhänge.',
    uploadPdf: 'PDF hochladen',
    uploaded: 'PDF hochgeladen',
    removeAttachment: 'Anhang entfernen',
    preview: 'Vorschau im Literaturverzeichnis',
    inProjects: 'In Projekten',
    namesHint: 'Mehrere Personen mit „;“ trennen, jeweils „Nachname, Vorname“.',
    dateHint: 'JJJJ, JJJJ-MM oder JJJJ-MM-TT',
  },
  addItem: {
    button: 'Titel hinzufügen',
    title: 'Titel hinzufügen',
    chooseDescription: 'Wie möchtest du den Titel hinzufügen?',
    back: 'Zurück',
    done: 'Fertig',
    methods: {
      identifier: {
        title: 'Per Nummer oder Link',
        description: 'DOI, ISBN, arXiv-ID, PubMed-ID oder Webseiten-URL – die Angaben werden automatisch geholt.',
      },
      manual: {
        title: 'Manuell erfassen',
        description: 'Für Titel ohne Nummer, z. B. Normen, Abschlussarbeiten oder graue Literatur.',
      },
      import: {
        title: 'Datei importieren',
        description: 'Aus Citavi, Zotero, EndNote oder Mendeley: BibTeX, RIS, EndNote Tagged, CSL-JSON oder ZIP mit PDFs.',
      },
    },
    identifierLabel: 'Nummer oder Link',
    identifierPlaceholder: 'z. B. 10.1038/nature14539',
    examples: 'Beispiele – zum Ausprobieren anklicken:',
    detectedAs: (type: string) => `Erkannt: ${type}`,
    notDetected: 'Noch nichts erkannt – DOI, ISBN, arXiv-ID, PMID oder URL eingeben.',
    search: 'Suchen und hinzufügen',
    searching: 'Suche Metadaten …',
    searchingHint: 'Frage doi.org, Crossref, DNB, swisscovery, arXiv oder PubMed an.',
    added: 'Zum Projekt hinzugefügt',
    alreadyInLibrary: 'War schon in deiner Bibliothek – jetzt auch in diesem Projekt.',
    addAnother: 'Weiteren Titel hinzufügen',
    openItem: 'Titel öffnen',
    notFound: 'Dazu wurden keine Angaben gefunden.',
    tryManual: 'Stattdessen manuell erfassen',
    chooseType: 'Welche Art von Titel?',
    save: 'Titel speichern',
    saved: 'Titel gespeichert',
    requiredTitle: 'Mindestens der Titel wird benötigt.',
    dropTitle: 'Datei hierher ziehen oder klicken zum Auswählen',
    dropHint:
      '.bib, .ris, .enw, .json oder .zip – z. B. ein Export aus Citavi (Projekt → Exportieren); als ZIP samt Ordner „Attachments“ werden die PDFs angehängt.',
    importing: 'Importiere …',
    importDone: 'Import abgeschlossen',
    importedCount: (n: number) => `${n} ${n === 1 ? 'Titel' : 'Titel'} neu hinzugefügt`,
    skippedCount: (n: number) => `${n} bereits vorhanden (dem Projekt zugeordnet)`,
    updatedCount: (n: number) => `${n} davon um fehlende Angaben ergänzt`,
    attachmentsCount: (n: number) => `${n} ${n === 1 ? 'PDF' : 'PDFs'} angehängt`,
    importAnother: 'Weitere Datei importieren',
  },
  itemTypes: {
    book: 'Buch',
    'article-journal': 'Zeitschriftenartikel',
    webpage: 'Webseite',
    'paper-conference': 'Konferenzbeitrag',
    standard: 'Norm',
    thesis: 'Abschlussarbeit',
    chapter: 'Buchkapitel',
    article: 'Preprint / Artikel',
    'article-newspaper': 'Zeitungsartikel',
    'article-magazine': 'Magazinartikel',
    report: 'Bericht',
    manuscript: 'Manuskript',
    legislation: 'Gesetz',
    legal_case: 'Urteil',
    patent: 'Patent',
    software: 'Software',
    dataset: 'Datensatz',
    document: 'Dokument',
  } as Record<string, string>,
  itemFields: {
    title: 'Titel',
    author: 'Autor:innen',
    editor: 'Herausgeber:innen',
    edition: 'Auflage',
    publisher: 'Verlag / Institution',
    'publisher-place': 'Ort',
    issued: 'Erscheinungsdatum',
    accessed: 'Zugriff am',
    ISBN: 'ISBN',
    DOI: 'DOI',
    URL: 'URL',
    'container-title': 'Erschienen in',
    volume: 'Band / Jahrgang',
    issue: 'Heft',
    page: 'Seiten',
    event: 'Konferenz',
    genre: 'Art (z. B. DIN EN ISO, Bachelorarbeit)',
    number: 'Nummer',
  } as Record<string, string>,
  importExport: {
    import: 'Importieren',
    importTitle: 'Titel importieren',
    importDescription: 'BibTeX (.bib), RIS (.ris), EndNote Tagged (.enw) oder CSL-JSON (.json) – z. B. ein Citavi-Export.',
    chooseFile: 'Datei wählen',
    importing: 'Importiere …',
    imported: (imported: number, skipped: number) =>
      `${imported} Titel importiert${skipped ? `, ${skipped} bereits vorhanden` : ''}`,
    export: 'Exportieren',
    formats: { bibtex: 'BibTeX', ris: 'RIS', 'csl-json': 'CSL-JSON' },
  },
  bibliography: {
    title: 'Literaturverzeichnis',
    filePrefix: 'Literaturverzeichnis',
    empty: 'Dieses Projekt enthält noch keine Titel.',
    copy: 'Kopieren',
    copied: 'Literaturverzeichnis kopiert',
    exportDocx: 'Word (DOCX)',
    exportMarkdown: 'Markdown',
    exportBibtex: 'BibTeX',
    style: (title: string) => `Zitierstil: ${title}`,
  },
  errors: {
    notAvailable: 'Diese Funktion gibt es nur, wenn OpenLitBase mit Login betrieben wird.',
    itemNotFound: 'Titel nicht gefunden.',
    projectNotFound: 'Projekt nicht gefunden.',
    fileNotFound: 'Datei nicht gefunden.',
    unknownIdentifier: 'Keine DOI, ISBN, arXiv-ID, PMID oder URL erkannt.',
    notResolved: 'Zu dieser Angabe wurden keine Metadaten gefunden.',
    unknownStyle: 'Unbekannter Zitierstil.',
    noFile: 'Keine Datei hochgeladen.',
    pdfOnly: 'Nur PDF-Dateien sind erlaubt.',
    fileTooLarge: 'Die Datei ist zu gross (max. 50 MB).',
    importFailed: 'Die Datei konnte nicht gelesen werden.',
    zipWithoutReferences: 'Im ZIP fehlt eine Literaturdatei (.ris, .bib, .enw oder .json).',
    zipTooLarge: 'Das ZIP ist zu gross (max. 300 MB).',
    tokenNotFound: 'Token nicht gefunden.',
    readOnly: 'Du hast in diesem Projekt nur Lesezugriff.',
    ownerOnly: 'Das darf nur die Person, der das Projekt gehört.',
    memberNotFound: 'Person nicht gefunden.',
    memberExists: 'Diese Person hat schon Zugriff auf das Projekt.',
    inviteSelf: 'Du hast bereits Zugriff auf dieses Projekt.',
    sharingSingleMode: 'Teilen gibt es nur, wenn OpenLitBase mit Login betrieben wird.',
    accountBlocked:
      'Dein Konto ist gesperrt, weil deine Institution nicht (mehr) freigegeben ist. Wende dich an die Administration.',
    adminOnly: 'Nur für Administrator:innen.',
    domainExists: 'Diese Domain ist bereits eingetragen.',
    domainNotFound: 'Domain nicht gefunden.',
    domainInUse: (count: number) =>
      `Löschen nicht möglich: ${count === 1 ? '1 Konto nutzt' : `${count} Konten nutzen`} diese Domain. Stattdessen deaktivieren.`,
    logoInvalid: 'Das Logo muss eine Bilddatei (z. B. PNG, JPG, WebP, SVG) bis 5 MB sein.',
    logoNotSquare: (width: number, height: number) =>
      `Das Logo muss quadratisch sein (1:1) – die Datei hat ${width} × ${height} px.`,
  },
  overview: {
    createdAt: (date: string) => `Angelegt am ${date}`,
    researchTitle: 'Forschungsdreisatz',
    researchDescription: 'Worum es in deiner Arbeit geht – in einem Satz.',
    researchEmptyTitle: 'Worum geht es in deinem Projekt?',
    researchEmptyDescription:
      'Der Forschungsdreisatz bringt Thema, Erkenntnisinteresse und Relevanz in einen Satz – die Grundlage für deine Forschungsfrage. Der Assistent führt dich in vier Schritten dorthin.',
    startAssistant: 'Mit dem Assistenten formulieren',
    editAssistant: 'Bearbeiten',
    questionTitle: 'Forschungsfrage',
    questionMissing: 'Noch keine Forschungsfrage festgehalten.',
    stats: {
      items: 'Titel',
      itemsHint: 'im Projekt',
      bibliography: 'Literaturverzeichnis',
      protocol: 'Rechercheprotokoll',
      protocolHint: 'Titel eingeordnet',
      matrix: 'Begriffsmatrix',
      matrixHint: (terms: number) => `${terms} ${terms === 1 ? 'Begriff' : 'Begriffe'}`,
      topics: (n: number) => `${n} ${n === 1 ? 'Teilthema' : 'Teilthemen'}`,
    },
    nextTitle: 'Nächste Schritte',
    nextProgress: (done: number, total: number) => `${done} von ${total} erledigt`,
    next: {
      triad: 'Forschungsdreisatz formulieren',
      question: 'Forschungsfrage festhalten',
      matrix: 'Suchbegriffe in der Begriffsmatrix sammeln',
      protocol: 'Titel im Rechercheprotokoll einordnen',
      items: 'Titel ins Projekt übernehmen',
    },
    recentTitle: 'Zuletzt hinzugefügt',
    recentEmpty: 'Noch keine Titel im Projekt.',
    allItems: 'Alle Titel',
    peopleTitle: 'Team',
  },
  research: {
    title: 'Forschungsdreisatz',
    description: 'Thema, Erkenntnisinteresse, Relevanz und Forschungsfrage in vier Schritten.',
    steps: {
      topic: {
        label: 'Thema',
        title: 'Was untersuchst du?',
        frame: 'Ich untersuche …',
        hint: 'Möglichst konkret – eingegrenzt nach Gegenstand, Gruppe, Ort oder Zeitraum.',
        placeholder: 'die Nutzung von KI-Schreibwerkzeugen im Bachelorstudium',
      },
      knowledgeGoal: {
        label: 'Erkenntnisinteresse',
        title: 'Was willst du herausfinden?',
        frame: '…, weil ich herausfinden möchte, …',
        hint: 'Als indirekte Frage, z. B. mit „wie“, „warum“ oder „ob“.',
        placeholder: 'wie Studierende diese Werkzeuge beim Schreiben einsetzen',
      },
      relevance: {
        label: 'Relevanz',
        title: 'Wozu ist das wichtig?',
        frame: '…, um …',
        hint: 'Was können andere mit deiner Antwort anfangen?',
        placeholder: 'zu verstehen, welche Unterstützung Hochschulen anbieten sollten',
      },
      question: {
        label: 'Forschungsfrage',
        title: 'Wie lautet deine Forschungsfrage?',
        hint: 'Eine offene Frage, die deine Arbeit beantwortet.',
        placeholder: 'Wie setzen Studierende KI-Schreibwerkzeuge beim Verfassen ihrer Abschlussarbeit ein?',
        checks: {
          questionMark: 'Eine Frage endet mit einem Fragezeichen.',
          open: 'Offen formulieren – mit „Wie“, „Warum“ oder „Inwiefern“ statt „Ist“ oder „Gibt es“.',
          length: 'Präzise, aber vollständig: 6 bis 40 Wörter.',
        },
      },
    },
    back: 'Zurück',
    next: 'Weiter',
    save: 'Speichern',
    saved: 'Forschungsdreisatz gespeichert',
  },
  protocol: {
    title: 'Rechercheprotokoll',
    filePrefix: 'Rechercheprotokoll',
    description: 'Dreisatz, Begriffsmatrix, eingeordnete Titel und Bibliografie – als Word-Dokument für den Anhang deiner Arbeit.',
    triad: 'Fragestellungs-Dreisatz',
    question: 'Forschungsfrage',
    matrix: 'Begriffsmatrix',
    titles: 'Liste der recherchierten Titel',
    titlesHint: 'Pro Titel einordnen – die Nummern entsprechen der Bibliografie.',
    bibliography: 'Bibliografie',
    columns: {
      number: 'Lfd. Nr.',
      citation: 'Zitation im Text',
      type: 'Dokumententyp',
      keywords: 'Themeneinordnung, Schlüsselbegriffe',
      suitability: 'Fachliche Eignung für die Entwicklung der Fragestellung',
    },
    matrixColumns: {
      term: 'Begriffe',
      synonyms: 'Synonyme',
      broader: 'Oberbegriffe',
      narrower: 'Unterbegriffe',
      related: 'Verwandt',
      opposite: 'Gegensätzlich',
      english: 'Englisch',
    },
    placeholders: {
      citation: 'z. B. „… wie Muster zeigt [3]“',
      keywords: 'z. B. Datenschutz, Trainingsdaten',
      suitability: 'Was trägt der Titel zu deiner Fragestellung bei?',
    },
    cardTitle: 'Rechercheprotokoll',
    cardDescription: 'Einordnung dieses Titels für das Rechercheprotokoll des Projekts.',
    saved: 'Gespeichert',
    download: 'Als Word herunterladen',
    downloadMarkdown: 'Als Markdown',
    editTriad: 'Zur Übersicht',
    editMatrix: 'Zur Begriffsmatrix',
    triadMissing: 'Noch kein Dreisatz – auf der Übersicht mit dem Assistenten formulieren.',
    matrixEmpty: 'Noch keine Begriffe gesammelt.',
    open: 'Titel öffnen',
  },
  termMatrix: {
    title: 'Begriffsmatrix',
    filePrefix: 'Begriffsmatrix',
    create: 'Erstes Teilthema anlegen',
    addColumn: 'Teilthema hinzufügen',
    columnPlaceholder: 'Hauptbegriff',
    newColumn: (n: number) => `Teilthema ${n}`,
    removeColumn: 'Teilthema entfernen',
    removeColumnTitle: 'Teilthema entfernen?',
    removeColumnDescription: (title: string) => `„${title}“ und alle Begriffe dieser Spalte werden entfernt.`,
    termPlaceholder: 'Begriff + Enter',
    truncateHint: 'Klick auf einen Begriff schaltet die Trunkierung (*) um – nur bei einzelnen Wörtern.',
    removeTerm: (term: string) => `„${term}“ entfernen`,
    rows: {
      title: 'Hauptbegriff',
      synonyms: 'Synonyme',
      broader: 'Oberbegriffe',
      narrower: 'Unterbegriffe',
      related: 'Verwandte Begriffe',
      opposite: 'Gegensätzliche Begriffe',
      english: 'Englische Übersetzungen',
    },
    saving: 'Speichert …',
    savedState: 'Gespeichert',
    searchString: 'Suchstring',
    searchStringDescription: 'Begriffe einer Spalte mit OR, Spalten mit AND verknüpft. Welche Zeilen einfliessen:',
    searchStringEmpty: 'Noch keine Begriffe in den gewählten Zeilen.',
    copy: 'Kopieren',
    copied: 'Suchstring kopiert',
    exportDocx: 'Word (DOCX)',
    exportMarkdown: 'Markdown',
  },
  settings: {
    title: 'Einstellungen',
    citationTitle: 'Zitierstil',
    citationDescription:
      'Standard für alle Projekte ohne eigenen Stil. Weitere Stile: .csl-Datei in den Ordner custom-styles legen.',
    saved: 'Einstellungen gespeichert',
    passwordTitle: 'Passwort ändern',
    passwordDescription: 'Nach dem Ändern wirst du auf allen anderen Geräten abgemeldet und erhältst eine Bestätigung per E-Mail.',
    currentPassword: 'Aktuelles Passwort',
    newPassword: 'Neues Passwort',
    confirmPassword: 'Neues Passwort wiederholen',
    passwordMismatch: 'Die neuen Passwörter stimmen nicht überein.',
    passwordSubmit: 'Passwort ändern',
    passwordChanged: 'Passwort geändert',
    wrongPassword: 'Das aktuelle Passwort ist falsch.',
    versionTitle: 'Version',
    versionCurrent: (v: string) => `Installiert: ${v}`,
    versionLatest: 'Du nutzt die neueste Version.',
    versionUpdate: (v: string) => `Version ${v} ist verfügbar.`,
    versionUpdateLink: 'Was ist neu?',
    versionOff: 'Die Update-Prüfung ist ausgeschaltet (UPDATE_CHECK=off).',
    versionPending: 'Noch nicht geprüft.',
    versionPrivacy:
      'Zur Update-Prüfung sendet OpenLitBase täglich nur Version, Modus und eine zufällige Instanz-ID an get.openlitbase.de – keine Inhalte, keine Personendaten.',
    deleteTitle: 'Konto löschen',
    deleteDescription: 'Löscht dein Konto und deine Daten endgültig. Das lässt sich nicht rückgängig machen.',
    deleteRemoves: [
      'deine Projekte samt Begriffsmatrix und Rechercheprotokoll',
      'Titel, Notizen und PDFs, die nur in deinen Projekten liegen',
      'API-Tokens, Einstellungen und alle Anmeldungen',
    ],
    deleteKeeps:
      'Titel, die du in geteilte Projekte anderer eingebracht hast, bleiben dort und gehören danach der Person, der das Projekt gehört.',
    deleteExportHint: 'Tipp: Exportiere vorher deine Titel – in einem Projekt unter Titel → Exportieren.',
    deletePassword: 'Passwort zur Bestätigung',
    deleteSubmit: 'Konto löschen …',
    deleteConfirmTitle: 'Konto wirklich löschen?',
    deleteConfirmText: 'Dein Konto und deine Daten werden sofort und endgültig gelöscht. Du erhältst eine Bestätigung per E-Mail.',
    deleteConfirm: 'Endgültig löschen',
    deleteWrongPassword: 'Das Passwort ist falsch.',
    deleted: 'Dein Konto wurde gelöscht.',
  },
  legal: {
    imprint: 'Impressum',
    privacy: 'Datenschutz',
    terms: 'Nutzungsbedingungen',
    source: 'Quellcode (AGPL)',
  },
  auth: {
    welcome: 'Willkommen bei OpenLitBase',
    consentBefore: 'Ich akzeptiere die ',
    consentAnd: ' und habe die ',
    consentAfter: ' zur Kenntnis genommen.',
    consentPrivacyOnly: 'Ich habe die ',
    consentTermsOnly: 'Ich akzeptiere die ',
    consentTermsLink: 'Nutzungsbedingungen',
    consentPrivacyLink: 'Datenschutzerklärung',
    consentRequired: 'Bitte stimme den Nutzungsbedingungen und der Datenschutzerklärung zu.',
    tagline: 'Literatur sammeln, zitieren und dokumentieren – für Studium und Forschung.',
    signIn: 'Anmelden',
    signUp: 'Registrieren',
    signOut: 'Abmelden',
    email: 'E-Mail',
    password: 'Passwort',
    passwordHint: 'Mindestens 8 Zeichen',
    name: 'Name',
    namePlaceholder: 'Vorname Nachname',
    signInSubmit: 'Anmelden',
    signUpSubmit: 'Konto erstellen',
    forgotPassword: 'Passwort vergessen?',
    availableFor: 'Verfügbar für',
    noInstitutions: 'Derzeit ist keine Institution freigegeben.',
    checkInbox: (email: string) =>
      `Fast geschafft: Wir haben einen Bestätigungslink an ${email} geschickt. Bitte E-Mail öffnen und den Link anklicken.`,
    notVerified: 'Bitte bestätige zuerst deine E-Mail-Adresse.',
    resendVerification: 'Bestätigungslink erneut senden',
    verificationSent: 'Bestätigungslink gesendet',
    invalidCredentials: 'E-Mail oder Passwort ist falsch.',
    linkInvalid: 'Der Link ist ungültig oder abgelaufen. Bitte fordere einen neuen an.',
    domainNotAllowed: (domains: string[]) =>
      domains.length > 0
        ? `Registrierung nur mit einer E-Mail-Adresse einer freigegebenen Institution möglich (${domains.join(', ')}).`
        : 'Registrierung ist derzeit für keine Institution freigegeben.',
    forgotTitle: 'Passwort zurücksetzen',
    forgotDescription: 'Gib deine E-Mail-Adresse ein. Du erhältst einen Link zum Zurücksetzen.',
    forgotSubmit: 'Link senden',
    forgotSent: 'Falls ein Konto mit dieser Adresse existiert, ist der Link unterwegs.',
    resetTitle: 'Neues Passwort festlegen',
    resetSubmit: 'Passwort speichern',
    resetDone: 'Passwort geändert. Du kannst dich jetzt anmelden.',
    newPassword: 'Neues Passwort',
    backToLogin: 'Zurück zur Anmeldung',
    account: 'Konto',
    blockedTitle: 'Zugang gesperrt',
  },
  emails: {
    greeting: (name: string) => (name ? `Hallo ${name}` : 'Hallo'),
    fallbackLink: 'Falls der Knopf nicht funktioniert, öffne diesen Link im Browser:',
    footer: 'Literatur sammeln, zitieren und dokumentieren – für Studium und Forschung.',
    automatic: 'Diese E-Mail wurde automatisch verschickt. Antworten erreichen niemanden.',
    verify: {
      subject: 'Bestätige deine E-Mail-Adresse',
      preheader: 'Noch ein Klick, dann ist dein OpenLitBase-Konto bereit.',
      title: 'Willkommen bei OpenLitBase',
      intro: 'Bitte bestätige deine E-Mail-Adresse. Danach wirst du automatisch angemeldet und kannst dein erstes Projekt anlegen.',
      button: 'E-Mail-Adresse bestätigen',
      note: 'Der Link ist 1 Stunde gültig. Falls du dich nicht registriert hast, kannst du diese E-Mail ignorieren.',
    },
    reset: {
      subject: 'Passwort zurücksetzen',
      preheader: 'Lege ein neues Passwort für dein OpenLitBase-Konto fest.',
      title: 'Neues Passwort festlegen',
      intro: 'Du hast angefordert, dein Passwort zurückzusetzen. Über den Link unten legst du ein neues fest – danach wirst du auf allen Geräten abgemeldet.',
      button: 'Neues Passwort festlegen',
      note: 'Der Link ist 1 Stunde gültig. Falls du das nicht angefordert hast, ignoriere diese E-Mail – dein Passwort bleibt unverändert.',
    },
    invite: {
      subject: (inviter: string, project: string) => `${inviter} hat dich zu „${project}“ eingeladen`,
      preheader: (project: string) => `Gemeinsam an „${project}“ arbeiten – in OpenLitBase.`,
      title: 'Einladung zu einem Projekt',
      access: (role: 'editor' | 'viewer') => (role === 'editor' ? 'mitarbeiten' : 'alles ansehen'),
      introExisting: (inviter: string, project: string, access: string) =>
        `${inviter} teilt das Projekt „${project}“ in OpenLitBase mit dir – du kannst ${access}. Du findest es ab sofort in deiner Projektliste.`,
      introNew: (inviter: string, project: string, access: string) =>
        `${inviter} möchte das Projekt „${project}“ in OpenLitBase mit dir teilen – du kannst ${access}. Erstelle dazu ein Konto mit dieser E-Mail-Adresse; das Projekt erscheint danach automatisch.`,
      buttonExisting: 'Projekt öffnen',
      buttonNew: 'Konto erstellen',
      note: 'Du erhältst diese E-Mail, weil deine Adresse für das Projekt eingetragen wurde. Wenn du nicht mitmachen möchtest, kannst du sie ignorieren.',
    },
    accountDeleted: {
      subject: 'Dein OpenLitBase-Konto wurde gelöscht',
      preheader: 'Dein Konto und deine Daten wurden gelöscht.',
      title: 'Konto gelöscht',
      intro:
        'Dein OpenLitBase-Konto wurde auf deinen Wunsch gelöscht – samt deinen Projekten, Titeln und PDFs. Aus den Sicherungskopien verschwinden die Daten nach Ablauf der Aufbewahrungsfrist.',
      button: 'Zu OpenLitBase',
      note: 'Warst du das nicht? Melde dich umgehend bei der Administration.',
    },
    passwordChanged: {
      subject: 'Dein Passwort wurde geändert',
      preheader: 'Das Passwort deines OpenLitBase-Kontos wurde soeben geändert.',
      title: 'Passwort geändert',
      intro: 'Das Passwort deines OpenLitBase-Kontos wurde soeben geändert. Anmeldungen auf anderen Geräten wurden beendet.',
      button: 'Zur Anmeldung',
      note: 'Warst du das nicht? Setze dein Passwort sofort über „Passwort vergessen?“ auf der Anmeldeseite zurück und informiere die Administration.',
    },
  },
  sharing: {
    share: 'Teilen',
    title: 'Projekt teilen',
    description:
      'Lade Personen deiner Institution ein. Wer schon ein Konto hat, sieht das Projekt sofort – alle anderen erhalten eine Einladung zur Registrierung.',
    viewDescription: 'Diese Personen haben Zugriff auf das Projekt.',
    email: 'E-Mail-Adresse',
    emailPlaceholder: 'name@hochschule.ch',
    invite: 'Einladen',
    invited: (email: string) => `${email} eingeladen`,
    inviteMailFailed: 'Eingetragen, aber die E-Mail konnte nicht verschickt werden.',
    roles: { owner: 'Besitzer:in', editor: 'Bearbeiten', viewer: 'Lesen' },
    roleHints: {
      editor: 'Titel, Protokoll, Matrix und Dreisatz bearbeiten',
      viewer: 'Alles ansehen und exportieren',
    },
    pending: 'Einladung offen',
    you: 'du',
    remove: 'Zugriff entfernen',
    removeTitle: 'Zugriff entfernen?',
    removeDescription: (name: string) =>
      `${name} verliert den Zugriff auf dieses Projekt. Bereits hinzugefügte Titel bleiben im Projekt.`,
    removed: 'Zugriff entfernt',
    leave: 'Projekt verlassen',
    leaveTitle: 'Projekt verlassen?',
    leaveDescription: 'Du verlierst den Zugriff auf das Projekt. Deine Beiträge bleiben im Projekt.',
    left: 'Projekt verlassen',
    roleChanged: 'Recht geändert',
    shared: 'Geteiltes Projekt',
    sharedWith: (n: number) => `Geteilt mit ${n} ${n === 1 ? 'Person' : 'Personen'}`,
    readOnly: 'Nur lesen',
    domainNotAllowed: (domains: string[]) =>
      `Einladen nur mit Adressen freigegebener Institutionen${domains.length > 0 ? ` (${domains.join(', ')})` : ''}.`,
  },
  tokens: {
    title: 'API-Tokens',
    description: 'Für Browser-Extension, Word-Add-in und KI-Agenten. Tokens wirken wie dein Login – nicht weitergeben.',
    empty: 'Noch keine Tokens.',
    create: 'Token erzeugen',
    nameLabel: 'Bezeichnung',
    namePlaceholder: 'z. B. Chrome Laptop',
    createdTitle: 'Token erzeugt',
    createdDescription: 'Kopiere den Token jetzt – er wird nur dieses eine Mal angezeigt.',
    copy: 'Kopieren',
    copied: 'Token kopiert',
    revoke: 'Widerrufen',
    revoked: 'Token widerrufen',
    createdAt: (date: string) => `erstellt ${date}`,
    lastUsed: (date: string | null) => (date ? `zuletzt genutzt ${date}` : 'noch nie genutzt'),
  },
  mcp: {
    title: 'KI-Agenten (MCP)',
    description:
      'Claude, ChatGPT, Cursor und andere KI-Agenten können über das Model Context Protocol auf deine Projekte zugreifen: Titel suchen und hinzufügen, Literaturverzeichnis, Begriffsmatrix und Forschungsdreisatz. Löschen können sie nichts.',
    urlLabel: 'Server-Adresse',
    commandLabel: 'Claude Code',
    tokenHint: 'Ersetze <TOKEN> durch einen API-Token (oben erzeugen). Der Agent hat damit dieselben Rechte wie du.',
    copy: 'Kopieren',
    copied: 'Kopiert',
  },
  bookmarklet: {
    title: 'Lesezeichen „Zu OpenLitBase“',
    description:
      'Für Safari, iPhone und iPad oder überall, wo die Browser-Extension fehlt: Auf einer Titelseite (Verlag, arXiv, Katalog) antippen – OpenLitBase öffnet sich mit dem erkannten Titel.',
    dragHint: 'Mac und PC: Den Knopf in die Lesezeichenleiste ziehen.',
    button: 'Zu OpenLitBase',
    iosHint:
      'iPhone und iPad: Diese Seite als Lesezeichen sichern, das Lesezeichen bearbeiten und die Adresse durch den kopierten Code ersetzen.',
    copy: 'Code kopieren',
    copied: 'Code kopiert',
    selectionHint: 'Tipp: Wird kein Titel erkannt (z. B. im Bibliothekskatalog), vorher die ISBN oder DOI markieren.',
    pageTitle: 'Titel übernehmen',
    noPage: 'Keine Seite übergeben. Das Lesezeichen „Zu OpenLitBase“ auf einer Titelseite antippen.',
    fromPage: (host: string) => `Von ${host}`,
    inputLabel: 'Nummer oder Link',
    projectLabel: 'Projekt',
    projectPlaceholder: 'Projekt wählen',
    noProjects: 'Du hast noch kein Projekt, in das du Titel legen darfst.',
    openApp: 'OpenLitBase öffnen',
    add: 'Übernehmen',
    close: 'Fenster schliessen',
  },
  admin: {
    nav: 'Administration',
    title: 'Administration',
    tabDomains: 'Institutionen',
    tabUsers: 'Nutzer:innen',
    domainsDescription:
      'Nur E-Mail-Adressen dieser Domains (inkl. Subdomains) können sich registrieren und anmelden.',
    addDomain: 'Institution hinzufügen',
    editDomain: 'Institution bearbeiten',
    domain: 'Domain',
    domainPlaceholder: 'z. B. hochschule.ch',
    name: 'Name',
    namePlaceholder: 'z. B. HSM – Hochschule Musterstadt',
    logo: 'Logo',
    users: 'Konten',
    status: 'Status',
    active: 'Aktiv',
    inactive: 'Deaktiviert',
    activate: 'Aktivieren',
    deactivate: 'Deaktivieren',
    deactivateTitle: (name: string) => `${name} deaktivieren?`,
    deactivateDescription: (count: number) =>
      `Neue Registrierungen werden gesperrt${count > 0 ? ` und ${count} bestehende${count === 1 ? 's Konto verliert' : ' Konten verlieren'} sofort den Zugriff (Web, Extension, Add-in)` : ''}. Admins sind ausgenommen.`,
    uploadLogo: 'Logo hochladen',
    removeLogo: 'Logo entfernen',
    logoHint: 'Quadratisch (1:1), beliebiges Bildformat bis 5 MB. Transparenz wird weiss hinterlegt.',
    delete: 'Löschen',
    deleteTitle: (name: string) => `${name} löschen?`,
    deleteDescription: 'Die Institution wird entfernt. Das geht nur, solange niemand mit dieser Domain registriert ist.',
    saved: 'Gespeichert',
    deleted: 'Institution gelöscht',
    usersDescription: 'Alle registrierten Konten (nur lesend).',
    searchUsers: 'Name oder E-Mail suchen …',
    noUsers: 'Noch keine Konten.',
    columns: {
      name: 'Name',
      email: 'E-Mail',
      institution: 'Institution',
      status: 'Status',
      createdAt: 'Registriert',
      lastSignIn: 'Letzte Anmeldung',
    },
    userStatus: {
      active: 'Aktiv',
      unverified: 'Unbestätigt',
      blocked: 'Gesperrt',
      admin: 'Admin',
    },
    never: 'nie',
  },
  addin: {
    title: 'Word-Add-in',
    manifestDescription: 'Titel aus OpenLitBase in Word zitieren und das Literaturverzeichnis automatisch erstellen.',
    ribbonButton: 'Zitieren',
    ribbonTooltip: 'OpenLitBase öffnen: Titel zitieren und Literaturverzeichnis einfügen.',
    notInWord: 'Vorschau im Browser – Zitieren und Literaturverzeichnis funktionieren nur in Word.',
    connectTitle: 'Mit OpenLitBase verbinden',
    connectDescription:
      'Erzeuge in OpenLitBase unter Einstellungen → API-Tokens einen Token und füge ihn hier ein.',
    openSettings: 'Einstellungen öffnen',
    tokenLabel: 'API-Token',
    tokenPlaceholder: 'olb_…',
    connect: 'Verbinden',
    invalidToken: 'Token ungültig oder widerrufen.',
    disconnect: 'Trennen',
    project: 'Projekt',
    projectPlaceholder: 'Projekt wählen',
    noProjectsTitle: 'Noch kein Projekt',
    noProjectsDescription: 'Lege in OpenLitBase ein Projekt an und füge Titel hinzu.',
    openApp: 'OpenLitBase öffnen',
    noItemsTitle: 'Keine Titel im Projekt',
    noItemsDescription: 'Füge in OpenLitBase Titel zu diesem Projekt hinzu.',
    search: 'Titel suchen …',
    doubleClickHint: 'Klick zeigt Details, Doppelklick fügt an der Cursorposition ein.',
    locator: 'Seite',
    locatorPlaceholder: '12',
    insertHere: 'An dieser Stelle einfügen',
    citing: 'Wird eingefügt …',
    insertBibliography: 'Literaturverzeichnis an aktueller Stelle einfügen',
    insertBibliographyTitle: 'Literaturverzeichnis einfügen?',
    insertBibliographyDescription:
      'Das Literaturverzeichnis wird als eigener Absatz an der Cursorposition eingefügt und beim Aktualisieren neu erstellt. Pro Dokument gibt es ein Verzeichnis.',
    insertBibliographyConfirm: 'Einfügen',
    bibliographyExists: 'Das Literaturverzeichnis ist schon im Dokument und wird mitaktualisiert.',
    refresh: 'Titel neu laden, Zitate und Literaturverzeichnis aktualisieren',
    refreshed: (citations: number, entries: number) =>
      `${citations} ${citations === 1 ? 'Zitat' : 'Zitate'} und ${entries} ${entries === 1 ? 'Eintrag' : 'Einträge'} aktualisiert`,
    cited: 'Zitat eingefügt',
    bibliographyInserted: 'Literaturverzeichnis eingefügt',
    bibliographyEmpty: 'Noch keine Zitate – das Literaturverzeichnis füllt sich beim Zitieren.',
    missingCitation: '[?]',
    wordError: 'Word hat die Änderung abgelehnt.',
  },
  extension: {
    title: 'Browser-Extension',
    settings: 'Einstellungen',
    back: 'Zurück',
    setup: {
      title: 'Wie nutzt du OpenLitBase?',
      description: 'Einmal einrichten – danach übernimmst du Titel direkt von Webseiten.',
      cloud: 'OpenLitBase Cloud',
      cloudHint: 'Konto auf cloud.openlitbase.de – nichts zu installieren.',
      selfHosted: 'Selbst gehostet',
      selfHostedHint: 'Eigene Installation – auf diesem Rechner oder bei deiner Institution.',
      serverTitle: 'Wo läuft OpenLitBase?',
      serverLabel: 'Adresse',
      serverHint: 'Auf diesem Rechner meist http://localhost:1450',
      tokenTitle: 'Mit deinem Konto verbinden',
      tokenHint: (host: string) =>
        `Melde dich auf ${host} an und erzeuge unter Einstellungen → API-Tokens einen Token für die Extension.`,
      tokenLabel: 'API-Token',
      openTokens: 'Token erzeugen',
      connect: 'Verbinden',
      connecting: 'Verbinde …',
      back: 'Zurück',
      invalidToken: 'Token ungültig oder widerrufen.',
      connection: 'Verbindung',
      change: 'Verbindung ändern',
    },
    pickerEnabled: 'Picker und Übernehmen-Symbol auf Webseiten',
    unreachable: 'Server nicht erreichbar – Adresse prüfen.',
    reloadPage: 'Die Extension wurde aktualisiert – bitte Seite neu laden.',
    unauthorized: 'Nicht angemeldet – API-Token in den Einstellungen der Extension prüfen.',
    noProject: 'Kein Projekt gewählt – im Popup der Extension auswählen.',
    project: 'Aktives Projekt',
    projectHint: 'Picker und Übernehmen-Symbol schreiben in dieses Projekt.',
    island: {
      label: 'Titel erkannt',
      add: 'Übernehmen',
      adding: 'Wird übernommen …',
      done: 'Übernommen',
      retry: 'Erneut versuchen',
      close: 'Ausblenden',
    },
    added: (title: string) => `Übernommen: ${title}`,
    alreadyAdded: (title: string) => `Schon vorhanden, dem Projekt zugeordnet: ${title}`,
    pickerTitle: 'In OpenLitBase übernehmen',
    recentTitle: 'Zuletzt übernommen',
    recentEmpty: 'Noch nichts übernommen.',
    openApp: 'OpenLitBase öffnen',
  },
} as const
